title: Web Development and User Experience
baseURL: http://wdux1718.bbkweb.org/
languagecode: en-gb
defaultlayout: page
disablekinds: [taxonomy, taxonomyTerm, RSS, sitemap, robotsTXT]
disablehugogeneratorinject: true
metadataformat: yaml
pluralizelisttitles: false
sectionpagesmenu: main
theme: bbkweb
blackfriday:
  hrefTargetBlank: true
params:
  longyear: "2017/2018"
  shortyear: "1718"
  shortname: "wdux"
  url: "wdux1718.bbkweb.org"
  session01name: WDUX01
  session01date: "02.10.18"
  session01time: "18.00-21.00"
  session01tutors: "Ines Rebelo/Rebekah Cupitt/Tim Priestman"
  session01place: "IT LAB"
  session02name: WDUX02
  session02date: "06.10.18"
  session02time: "09:30-16:30"
  session02tutors: "Giacomo Sorbi/Maria Dada/Bhavik Sheth"
  session02place: "IT LAB"
  session03name: WDUX03
  session03date: "13.10.18"
  session03time: "09:30-16:30"
  session03tutors: "Ines Rebelo/Rebekah Cupitt"
  session03place: "Class Room"
  session04name: WDUX04
  session04date: "27.10.18"
  session04time: "09:30-16:30"
  session04tutors: "Giacomo Sorbi/Maria Dada/Bhavik Sheth"
  session04place: "IT LAB"
  session05name: WDUX05
  session05date: "10.11.18"
  session05time: "09:30-16:30"
  session05tutors: "Ines Rebelo/Rebekah Cupitt"
  session05place: "Class Room"
  session06name: WDUX06
  session06date: "24.11.18"
  session06time: "09:30-16:30"
  session06tutors: "Giacomo Sorbi/Maria Dada/Bhavik Sheth"
  session06place: "IT LAB"
  session07name: WDUX07
  session07date: "01.12.18"
  session07time: "09:30-16:30"
  session07tutors: "Ines Rebelo/Rebekah Cupitt"
  session07place: "Class Room"
  session08name: WDUX08
  session08date: "08.12.18"
  session08time: "18:00-21:00"
  session08tutors: "Giacomo Sorbi/Maria Dada/Bhavik Sheth"
  session08place: "IT LAB"
  session09name: WDUX09
  session09date: "11.12.18"
  session09time: "18.00-21.00"
  session09tutors: "Ines Rebelo/Rebekah Cupitt/Tim Priestman"
  session09place: "IT LAB"
  session10name: VDWP01
  session10date: "19.01.19"
  session10time: "09.30-16.30"
  session10tutors: "Giacomo Sorbi/Maria Dada/Bhavik Sheth"
  session10place: "IT LAB"
  session11name: VDWP02
  session11date: "22.01.19"
  session11time: "18.00-21.00"
  session11tutors: "Jonathan Fox/Ines Rebelo"
  session11place: "IT LAB"
  session12name: VDWP03
  session12date: "29.01.19"
  session12time: "18.00-21.00"
  session12tutors: "Jonathan Fox/Ines Rebelo"
  session12place: "IT LAB"
  session13name: VDWP04
  session13date: "09.02.19"
  session13time: "09.30-16.30"
  session13tutors: "Giacomo Sorbi/Maria Dada/Bhavik Sheth"
  session13place: "IT LAB"
  session14name: VDWP05
  session14date: "12.02.19"
  session14time: "18.00-21.00"
  session14tutors: "Jonathan Fox/Ines Rebelo"
  session14place: "IT LAB"
  session15name: VDWP06
  session15date: "19.02.19"
  session15time: "18.00-21.00"
  session15tutors: "Jonathan Fox/Ines Rebelo"
  session15place: "IT LAB"
  session16name: VDWP07
  session16date: "02.03.19"
  session16time: "09.30-16.30"
  session16tutors: "Giacomo Sorbi/Maria Dada/Bhavik Sheth"
  session16place: "IT LAB"
  session17name: VDWP08
  session17date: "05.03.19"
  session17time: "18.00-21.00"
  session17tutors: "Jonathan Fox/Ines Rebelo"
  session17place: "IT LAB"
  session18name: VDWP09
  session18date: "12.03.19"
  session18time: "18.00-21.00"
  session18tutors: "Jonathan Fox/Ines Rebelo"
  session18place: "IT LAB"
  session19name: VDWP10
  session19date: "19.03.19"
  session19time: "18.00-21.00"
  session19tutors: "Jonathan Fox/Ines Rebelo"
  session19place: "IT LAB"
  session20name: VDWP11
  session20date: "23.03.19"
  session20time: "09.30-16.30"
  session20tutors: "Giacomo Sorbi/Maria Dada/Bhavik Sheth"
  session20place: "IT LAB"
  assignmentdate: "2018-02-09"
