name = "bbkweb"
license = ""
licenselink = ""
description = "Theme for bbkweb.org subsites"
homepage = ""
tags = []
features = []
min_version = "0.29"

[author]
  name = "Ian Sealy"
  homepage = "http://www.iansealy.com/"

[original]
  name = ""
  homepage = ""
  repo = ""
